packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'apps/*'
catalog:
  vue: ^3.5.12
  pinia: ^2.2.5
  vue-router: ^4.4.5
  vite: ^5.4.10
  vitest: ^2.1.4
  typescript: ^5.6.3
  husky: ^9.1.6
  eslint: ^9.13.0
  stylelint: ^16.10.0
  prettier: ^3.3.3
  element-plus: ^2.8.6
  eslint-plugin-vue: ^9.30.0
  axios: ^1.7.7